#!/bin/bash

# Input parameters
ROOT_FOLDER=".."
CMAKE_BUILD_TYPE=Debug
IS_INSTALL=true
CMAKE_CXX_COMPILER=g++
CMAKE_CXX_FLAGS="-m64 -Wall -pedantic"

# Build project
cmake -S $ROOT_FOLDER -B $ROOT_FOLDER/build/$CMAKE_BUILD_TYPE \
    -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER \
    -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
    -DCMAKE_INSTALL_PREFIX=$ROOT_FOLDER/build_install/$CMAKE_BUILD_TYPE \
    -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS"
cmake --build $ROOT_FOLDER/build/$CMAKE_BUILD_TYPE --parallel 6

# Install project
if [ "$IS_INSTALL" = true ]; then
    cmake --install $ROOT_FOLDER/build/$CMAKE_BUILD_TYPE
fi
